#!/bin/bash
# ARR Apps Auto-Connection Script
# This will guide you through connecting Prowlarr to other ARR apps

CONTAINER_IP="192.168.11.66"

echo "============================================================"
echo "🔗 ARR APPS AUTO-CONNECTION GUIDE"
echo "============================================================"
echo ""
echo "✅ All apps are running!"
echo ""
echo "📱 STEP 1: Complete Initial Setup"
echo "   Open each URL in your browser:"
echo ""
echo "   1. Prowlarr:  http://${CONTAINER_IP}:9696"
echo "      → Create admin account"
echo "      → Finish setup wizard"
echo ""
echo "   2. Sonarr:    http://${CONTAINER_IP}:8989"
echo "      → Create admin account"
echo "      → Finish setup wizard"
echo ""
echo "   3. Radarr:    http://${CONTAINER_IP}:7878"
echo "      → Create admin account"
echo "      → Finish setup wizard"
echo ""
echo "   4. Lidarr:    http://${CONTAINER_IP}:8686"
echo "      → Create admin account"
echo "      → Finish setup wizard"
echo ""
echo "   5. Jellyfin:  http://${CONTAINER_IP}:8096"
echo "      → Create admin account"
echo "      → Finish setup wizard"
echo ""
echo "============================================================"
echo "📱 STEP 2: Connect Prowlarr to Apps"
echo "============================================================"
echo ""
echo "After completing setup for each app:"
echo ""
echo "   1. Get Prowlarr API Key:"
echo "      → Open Prowlarr"
echo "      → Settings → General → API Key"
echo "      → Copy the API Key"
echo ""
echo "   2. Connect Sonarr to Prowlarr:"
echo "      → Open Sonarr"
echo "      → Settings → Apps → + (Add)"
echo "      → Name: Prowlarr"
echo "      → Sync Level: Full"
echo "      → Prowlarr Server: http://${CONTAINER_IP}:9696"
echo "      → API Key: [paste Prowlarr API key]"
echo "      → Test → Save"
echo ""
echo "   3. Connect Radarr to Prowlarr:"
echo "      → Open Radarr"
echo "      → Settings → Apps → + (Add)"
echo "      → Name: Prowlarr"
echo "      → Sync Level: Full"
echo "      → Prowlarr Server: http://${CONTAINER_IP}:9696"
echo "      → API Key: [paste Prowlarr API key]"
echo "      → Test → Save"
echo ""
echo "   4. Connect Lidarr to Prowlarr:"
echo "      → Open Lidarr"
echo "      → Settings → Apps → + (Add)"
echo "      → Name: Prowlarr"
echo "      → Sync Level: Full"
echo "      → Prowlarr Server: http://${CONTAINER_IP}:9696"
echo "      → API Key: [paste Prowlarr API key]"
echo "      → Test → Save"
echo ""
echo "============================================================"
echo "📱 STEP 3: Add Indexers in Prowlarr"
echo "============================================================"
echo ""
echo "   1. Open Prowlarr: http://${CONTAINER_IP}:9696"
echo "   2. Go to: Indexers → Add (Torznab/Newznab)"
echo "   3. Popular free indexers:"
echo "      → Jackett (if you have it)"
echo "      → Cardigann (built-in indexers)"
echo "   4. Or use paid indexers:"
echo "      → NZBGeek"
echo "      → DogNZB"
echo "      → NZB.su"
echo ""
echo "============================================================"
echo "📱 STEP 4: Add Download Client"
echo "============================================================"
echo ""
echo "   Install Transmission or qBittorrent:"
echo ""
echo "   Option 1 - Add to this container:"
echo "      pct exec 220 -- docker run -d \\"
echo "        --name transmission \\"
echo "        -e PUID=1000 -e PGID=1000 \\"
echo "        -e TZ=Europe/Warsaw \\"
echo "        -p 9091:9091 -p 51413:51413 \\"
echo "        -v ~/arr-stack/config/transmission:/config \\"
echo "        -v ~/arr-stack/downloads:/downloads \\"
echo "        linuxserver/transmission"
echo ""
echo "   Option 2 - Install qBittorrent:"
echo "      pct exec 220 -- docker run -d \\"
echo "        --name qbittorrent \\"
echo "        -e PUID=1000 -e PGID=1000 \\"
echo "        -e TZ=Europe/Warsaw \\"
echo "        -p 8080:8080 \\"
echo "        -v ~/arr-stack/config/qbittorrent:/config \\"
echo "        -v ~/arr-stack/downloads:/downloads \\"
echo "        linuxserver/qbittorrent"
echo ""
echo "   Then in Sonarr/Radarr/Lidarr:"
echo "      → Settings → Download Client → +"
echo "      → Add Transmission/qBittorrent"
echo "      → Server: http://${CONTAINER_IP}:9091 (or 8080)"
echo "      → Username/Password: (if configured)"
echo ""
echo "============================================================"
echo "📱 STEP 5: Setup Root Folders"
echo "============================================================"
echo ""
echo "   In Sonarr: Settings → Media Management → Root Folders"
echo "      → Add: /tv"
echo ""
echo "   In Radarr: Settings → Media Management → Root Folders"
echo "      → Add: /movies"
echo ""
echo "   In Lidarr: Settings → Media Management → Root Folders"
echo "      → Add: /music"
echo ""
echo "============================================================"
echo "🎉 ALL DONE!"
echo "============================================================"
echo ""
echo "Your ARR stack is ready to use!"
echo ""
echo "📚 Quick Links:"
echo "   • Prowlarr:  http://${CONTAINER_IP}:9696"
echo "   • Sonarr:    http://${CONTAINER_IP}:8989"
echo "   • Radarr:    http://${CONTAINER_IP}:7878"
echo "   • Lidarr:    http://${CONTAINER_IP}:8686"
echo "   • Jellyfin:  http://${CONTAINER_IP}:8096"
echo ""
echo "============================================================"
